mode: MPIIGaze
device: cuda
dataset:
  dataset_dir: datasets/MPIIGaze.h5
model:
  name: lenet_attn
test:
  test_id: 1
  checkpoint: experiments/mpiigaze/lenet_attn/exp00/00/checkpoint_0010.pth
  output_dir: experiments/mpiigaze/lenet_attn/exp00/00/eval
  batch_size: 256
  dataloader:
    num_workers: 4
    pin_memory: False
cudnn:
  benchmark: True
  deterministic: False
